export const MFY_SUGGESTIONS: string[] = [
  "Chilonzor",
  "Oqtepa",
  "Yasamon",
  "Guliston",
  "Navbahor",
  "Chamanazor",
  "Qo'yliq",
  "Sergeli",
  "Yunusobod",
  "Olmazor",
  "Mustaqillik",
  "Do'stlik",
  "Yangi hayot",
  "Navro'z",
  "Bahor",
  "Zarafshon",
  "Mehnatobod",
  "Sog'lom",
  "Ipak yo'li",
  "Oltin vodiy",
  "Nurafshon",
  "Yangiobod",
  "Saroy",
  "Qo'rg'oncha",
  "Xonobod",
  "Chinor",
  "Bobur",
  "Alisher Navoiy",
  "Amir Temur",
  "Istiqlol",
  "Obod",
  "Yangi obod",
  "Gulshan",
  "Lola",
  "Nuroniy",
  "Kamalak",
  "Tekstil",
  "Quvachi",
  "Ko'hna qal'a",
  "Bog'ishamol",
];